// apps/frontend/portal/src/components/angular/api-call/api-call.component.ts
import {
    Component,
    signal,
    ChangeDetectionStrategy,
    OnInit,
} from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
    selector: 'app-api-call',
    standalone: true,
    templateUrl: './api-call.component.html',
    styleUrl: './api-call.component.css',
    imports: [CommonModule],
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ApiCallComponent implements OnInit {
    protected data = signal<string | null>(null);
    protected error = signal<string | null>(null);
    protected loading = signal(true);

    ngOnInit() {
        this.fetchData();
    }

    private async fetchData() {
        try {
            const response = await fetch('api/ping');
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            const text = await response.text();
            this.data.set(text);
            this.loading.set(false);
        } catch (err) {
            const errorMessage = err instanceof Error ? err.message : 'Unknown error';
            this.error.set(errorMessage);
            this.loading.set(false);
        }
    }
}

@if (error()) {
<p class="text-error">{{ error() }}</p>
}
@else if (data()) {
<pre>{{ data() }}</pre>
}
@else {
<p>Loading...</p>
}

// apps/frontend/portal/src/components/svelte/ApiCall.svelte
<script>
    import { onMount } from "svelte";

    let data = null;
    let error = null;

    onMount(async () => {
        try {
            const response = await fetch("api/ping");
            if (!response.ok) {
                throw new Error("Network response was not ok");
            }
            // data = await response.json();
            data = await response.text();
        } catch (err) {
            error = err.message;
        }
    });
</script>

{#if error}
    <p class="error">{error}</p>
{:else if data}
    <pre>{JSON.stringify(data, null, 2)}</pre>
{:else}
    <p>Loading...</p>
{/if}

<style>
    .error {
        color: red;
    }
</style>
