// apps/frontend/portal/src/components/LoginForm.svelte
<script lang="ts">
    import { Button } from "$lib/components/ui/button/index.js";
    import * as Card from "$lib/components/ui/card/index.js";
    import { Label } from "$lib/components/ui/label/index.js";
    import { Input } from "$lib/components/ui/input/index.js";
    import { cn } from "$lib/utils.js";
    import type { HTMLAttributes } from "svelte/elements";

    let { class: className, ...restProps }: HTMLAttributes<HTMLDivElement> =
        $props();

    const id = $props.id();
    import { authClient } from "./auth-client";

    function googleSignIn() {
        authClient.signIn.social(
            {
                provider: "google",
                callbackURL: "/",
            },
            {
                onSuccess: () => {
                    // Redirect to the dashboard or sign in page
                    console.log("Success");
                },
                onError: (ctx) => {
                    // Display the error message
                    console.error(ctx.error.message);
                    alert(ctx.error.message);
                },
            },
        );
    }
</script>

<div class={cn("flex flex-col gap-6", className)} {...restProps}>
    <Card.Root>
        <Card.Header class="text-center">
            <Card.Title class="text-xl">Welcome back</Card.Title>
            <Card.Description>Login with your Google account</Card.Description>
            <!-- <Card.Description>
                Login with your GitHub or Google account
            </Card.Description> -->
        </Card.Header>
        <Card.Content>
            <form>
                <div class="grid gap-6">
                    <div class="flex flex-col gap-4">
                        <!-- <Button variant="outline" class="w-full">
                            <svg
                                xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 24 24"
                            >
                                <path
                                    d="M12.152 6.896c-.948 0-2.415-1.078-3.96-1.04-2.04.027-3.91 1.183-4.961 3.014-2.117 3.675-.546 9.103 1.519 12.09 1.013 1.454 2.208 3.09 3.792 3.039 1.52-.065 2.09-.987 3.935-.987 1.831 0 2.35.987 3.96.948 1.637-.026 2.676-1.48 3.676-2.948 1.156-1.688 1.636-3.325 1.662-3.415-.039-.013-3.182-1.221-3.22-4.857-.026-3.04 2.48-4.494 2.597-4.559-1.429-2.09-3.623-2.324-4.39-2.376-2-.156-3.675 1.09-4.61 1.09zM15.53 3.83c.843-1.012 1.4-2.427 1.245-3.83-1.207.052-2.662.805-3.532 1.818-.78.896-1.454 2.338-1.273 3.714 1.338.104 2.715-.688 3.559-1.701"
                                    fill="currentColor"
                                />
                            </svg>
                            Login with GitHub
                        </Button> -->
                        <Button
                            variant="outline"
                            class="w-full"
                            onclick={() => googleSignIn()}
                        >
                            <svg
                                xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 24 24"
                            >
                                <path
                                    d="M12.48 10.92v3.28h7.84c-.24 1.84-.853 3.187-1.787 4.133-1.147 1.147-2.933 2.4-6.053 2.4-4.827 0-8.6-3.893-8.6-8.72s3.773-8.72 8.6-8.72c2.6 0 4.507 1.027 5.907 2.347l2.307-2.307C18.747 1.44 16.133 0 12.48 0 5.867 0 .307 5.387.307 12s5.56 12 12.173 12c3.573 0 6.267-1.173 8.373-3.36 2.16-2.16 2.84-5.213 2.84-7.667 0-.76-.053-1.467-.173-2.053H12.48z"
                                    fill="currentColor"
                                />
                            </svg>
                            Login with Google
                        </Button>
                    </div>
                    <!-- <div
                        class="after:border-border relative text-center text-sm after:absolute after:inset-0 after:top-1/2 after:z-0 after:flex after:items-center after:border-t"
                    >
                        <span
                            class="bg-card text-muted-foreground relative z-10 px-2"
                        >
                            Or continue with
                        </span>
                    </div>
                    <div class="grid gap-6">
                        <div class="grid gap-3">
                            <Label for="email-{id}">Email</Label>
                            <Input
                                id="email-{id}"
                                type="email"
                                placeholder="m@example.com"
                                required
                            />
                        </div>
                        <div class="grid gap-3">
                            <div class="flex items-center">
                                <Label for="password-{id}">Password</Label>
                                <a
                                    href="##"
                                    class="ml-auto text-sm underline-offset-4 hover:underline"
                                >
                                    Forgot your password?
                                </a>
                            </div>
                            <Input
                                id="password-{id}"
                                type="password"
                                required
                            />
                        </div>
                        <Button type="submit" class="w-full">Login</Button>
                    </div>
                    <div class="text-center text-sm">
                        Don&apos;t have an account?
                        <a href="/sign-up" class="underline underline-offset-4">
                            Sign up
                        </a>
                    </div> -->
                </div>
            </form>
        </Card.Content>
    </Card.Root>
    <div
        class="text-muted-foreground *:[a]:hover:text-primary *:[a]:underline *:[a]:underline-offset-4 text-balance text-center text-xs"
    >
        By clicking continue, you agree to our <a href="/terms-of-service"
            >Terms of Service</a
        >
        and <a href="/privacy-policy">Privacy Policy</a>.
    </div>
</div>

// apps/frontend/portal/src/app/components/login-form/login-form.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { createAuthClient } from 'better-auth/client';

@Component({
    selector: 'app-login-form',
    templateUrl: './login-form.component.html',
    styleUrl: './login-form.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LoginFormComponent {
    private authClient = createAuthClient({
        baseURL: typeof window !== 'undefined' && window.location.hostname === 'localhost'
            ? 'http://localhost:3000'
            : undefined,
    });

    protected googleSignIn(

    ): void {
        const callbackURL = typeof window !== 'undefined' && window.location.hostname === 'localhost'
            ? 'http://localhost:3001'
            : '/';

        this.authClient
            .signIn
            .social(
                {
                    provider: 'google',
                    callbackURL,
                },
                {
                    onSuccess: () => {
                        console.log('Google sign-in successful');
                    },
                    onError: (ctx) => {
                        console.error('Google sign-in error:', ctx.error.message);
                        // TODO: Replace alert with a modern notification system (e.g., toast)
                        alert(ctx.error.message);
                    },
                },
            );
    }
}

<div class="flex flex-col gap-6">
    <div class="card bg-base-100 shadow-xl">
        <div class="card-body">
            <h2 class="card-title text-xl text-center justify-center">Welcome back</h2>
            @if (authMode() === 'loading') {
                <div class="grid justify-items-center gap-3 py-6">
                    <span class="loading loading-spinner loading-md"></span>
                    <p class="text-center text-sm opacity-70">Loading sign-in options...</p>
                </div>
            } @else if (authMode() === 'master-password') {
                <p class="text-center text-sm opacity-70">Enter the master password to sign in</p>

                <form (ngSubmit)="signInWithMasterPassword()">
                    <div class="grid gap-6">
                        <div class="form-control">
                            <label class="label" for="master-password">
                                <span class="label-text">Master password</span>
                            </label>
                            <input
                                id="master-password"
                                name="masterPassword"
                                type="password"
                                class="input input-bordered w-full"
                                [ngModel]="masterPassword()"
                                (ngModelChange)="masterPassword.set($event)"
                                autocomplete="current-password"
                                required
                            />
                        </div>
                        <button
                            type="submit"
                            class="btn btn-primary w-full"
                            [disabled]="isSubmitting() || masterPassword().length === 0"
                        >
                            @if (isSubmitting()) {
                                <span class="loading loading-spinner loading-xs"></span>
                                Signing in...
                            } @else {
                                Sign in
                            }
                        </button>
                    </div>
                </form>
            } @else if (authMode() === 'google') {
                <p class="text-center text-sm opacity-70">Login with your Google account</p>

                <form>
                    <div class="grid gap-6">
                        <div class="flex flex-col gap-4">
                            <button
                                type="button"
                                class="btn btn-outline w-full"
                                (click)="googleSignIn()"
                            >
                                <svg
                                    xmlns="http://www.w3.org/2000/svg"
                                    viewBox="0 0 24 24"
                                    class="w-5 h-5"
                                >
                                    <path
                                        d="M12.48 10.92v3.28h7.84c-.24 1.84-.853 3.187-1.787 4.133-1.147 1.147-2.933 2.4-6.053 2.4-4.827 0-8.6-3.893-8.6-8.72s3.773-8.72 8.6-8.72c2.6 0 4.507 1.027 5.907 2.347l2.307-2.307C18.747 1.44 16.133 0 12.48 0 5.867 0 .307 5.387.307 12s5.56 12 12.173 12c3.573 0 6.267-1.173 8.373-3.36 2.16-2.16 2.84-5.213 2.84-7.667 0-.76-.053-1.467-.173-2.053H12.48z"
                                        fill="currentColor"
                                    />
                                </svg>
                                Login with Google
                            </button>
                        </div>
                    </div>
                </form>
            } @else {
                <div class="grid gap-4 py-2">
                    <p class="text-center text-sm text-error">
                        We couldn't load the available sign-in options.
                    </p>
                    <button
                        type="button"
                        class="btn btn-outline w-full"
                        (click)="retryLoadAuthConfig()"
                    >
                        Try again
                    </button>
                </div>
            }
        </div>
    </div>
    <div class="text-center text-xs text-base-content/60">
        By continuing, you agree to our
        <a href="/terms-of-service" class="link link-hover">Terms of Service</a>
        and
        <a href="/privacy-policy" class="link link-hover">Privacy Policy</a>.
    </div>
</div>
